import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Navbar from '../comps/navbar'
import Card from '../comps/card'
import { useState } from 'react'
import Footer from '../comps/footer'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export default function Home({newsinfo}) {

  return (
    <>
      <Head>
        <title>News Daily</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/6306bd6b99.js" crossOrigin="anonymous"></script>
      </Head>
      <Navbar/>
      <div className={styles.gallery}>
        {
          newsinfo.map((data,index)=>{
            // console.log(data);
            return <Link href={`/${data.id}`}><Card imge={data.image} title={data.title} tag={data.tag} smalldes={data.smalldes} user={data.user} timeline={data.timeline} key={index}/></Link>
          })
        }
      </div>

      <Footer/>

    </>
  )
}

export async function getStaticProps(){

  const res=await fetch('http://localhost:3000/newsinfo.json');
  const data=await res.json();
  console.log(data);
  return {
    props:{newsinfo: data}
  }
}